name: binpack
description: Simple library for 2D bin packing, as used for texture atlases.
version: 1.0.0
repository: https://github.com/bramp/binpack

environment:
  sdk: ^3.3.0

dependencies:
  collection: ^1.18.0

dev_dependencies:
  benchmark_harness: ^2.2.2
  lints: ^3.0.0
  test: ^1.24.0
