name: binpack
description: Simple library for 2D bin packing, as used for texture atlases.
version: 1.1.0
repository: https://github.com/bramp/binpack
# publish_to: https://pub.dev

environment:
  sdk: "^3.11.3"

dependencies:
  collection: ^1.19.1

dev_dependencies:
  benchmark_harness: ^2.4.0
  stats: ^3.0.0
  test: ^1.31.0
  very_good_analysis: ^10.2.0
